
sim_fun_GAM4 <- function(df_long, nsims=100){
  set.seed(8675309) # makes sure random numbers are reproducible
  results_out <- NULL
  for(i in 1:nsims){
    sim_df_long <- df_long 
    dummy_df_long <- sim_df_long %>% group_by(participant_id, child_adip_over) %>% dplyr::summarise(N=n())
    x <- table(dummy_df_long$child_adip_over)
    
    
    dummy2_df_long <- dummy_df_long %>% ungroup() %>%  dplyr::select(-N) %>% mutate(y=rbinom(sum(x), 1, x["Yes"]/sum(x))) %>% 
      mutate(m = ifelse(y==1, "Yes", "No"))
    
    
    sim_df_long <- sim_df_long %>% left_join(dplyr::select(dummy2_df_long, participant_id, m), by="participant_id")
    sim_df_long$child_adip_over <- sim_df_long$m
    
    
    
    sim_z <- ddply(sim_df_long, .(name), fun_inter_adj)
    sim_z$sim <- i
    results_out <- if (!is.null(results_out)) bind_rows(results_out, sim_z) else sim_z
  }
  results_out
}

sim_inter_centile_table <- function(results_out){
  sim_results_out <- results_out %>% group_by(name) %>% 
    dplyr::summarise(fifth_pctile=quantile(`value:gdm_pvalue`,0.05), ninetyfifth_pctile=quantile(`value:gdm_pvalue`,0.95), median=median(`value:gdm_pvalue`))
  sim_results_out  
}

sim_centile_inter <- function(results_out){
  sim_results_out <- results_out %>% group_by(name) %>% 
    dplyr::summarise(fifth_pctile=quantile(`value:gdm_pvalue`,0.05), ninetyfifth_pctile=quantile(`value:gdm_pvalue`,0.95), median=median(`value:gdm_pvalue`), median_gdm_pvalue=median(gdm_pvalue))
  sim_results_out  
}

sim_inter_indiv_plot <- function(long_data, long_filt_data, sig_data){
  plot <- long_data %>% mutate(name=factor(as.character(name),levels=unique(name))) %>%
    ggplot(aes(x = name, y = value, colour = type, group=type)) +
    geom_rect(xmin=0, xmax=98, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=98, xmax=168, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=168, xmax=171, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=171, xmax=180, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=180, xmax=189, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=189, xmax=192, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=192, xmax=208, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=208, xmax=213, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=213, xmax=222, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=222, xmax=225, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=225, xmax=227, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=227, xmax=228, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    annotate(geom="text", x=(xminval+xmaxval)/2, y=-0.07, label=as.factor(metgroup), size=5) +
    geom_point() + 
    geom_line(data=long_data[which(long_data$type != "real_pvalue"),], aes(x=name, y=value, group=type[which(type != "real_pvalue")])) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_text(size=14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(),
          axis.line = element_line(colour = "black", size=0.3),
          axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          plot.title = element_text(size=17),
          aspect.ratio=7/21,
          legend.title = element_text(face="bold", size=15), 
          legend.text = element_text(size=14),
          legend.position="bottom") +
    labs(title = "Comparison of p-values generated from simulated data against p-values from real data for metabolite abundance \nat individual visits, generated by fitting an interaction model.",
         x = "Individual Metabolite",
         y = "P-value") + 
    geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.3) +
    geom_point(data=long_filt_data[which(long_filt_data$type =="real_pvalue"),], aes(x = name, y = value, fill = "real_pvalue", group=type), shape=17, size=3.5) +
    scale_fill_manual("real data p-values \noutside range", values=rep(1,5), guide=guide_legend(override.aes = list(colour=c("#e76bf3")))) + 
    guides(colour = guide_legend(override.aes = list(shape = 20))) +
    annotate(geom = "text", x = sig_data$name, y = sig_data$`value:gdm_pvalue` - 0.03, label = rownames(sig_data), size = 5)
  plot
}

srfdr_inter_indiv_plot <- function(long_data, long_filt_data, sig_data){
  plot <- long_data %>% mutate(name=factor(as.character(name),levels=unique(name))) %>%
    ggplot(aes(x = name, y = value, colour = type, group=type)) +
    geom_rect(xmin=0, xmax=98, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=98, xmax=168, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=168, xmax=171, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=171, xmax=180, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=180, xmax=189, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=189, xmax=192, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=192, xmax=208, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=208, xmax=213, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=213, xmax=222, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=222, xmax=225, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=225, xmax=227, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=227, xmax=228, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    annotate(geom="text", x=(xminval+xmaxval)/2, y=-0.07, label=as.factor(metgroup), size=5) +
    geom_point() + 
    geom_line(data=long_data[which(long_data$type != "real_pvalue"),], aes(x=name, y=value, group=type[which(type != "real_pvalue")])) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_text(size=14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(),
          axis.line = element_line(colour = "black", size=0.3),
          axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          plot.title = element_text(size=17),
          aspect.ratio=7/21,
          legend.title = element_text(face="bold", size=15), 
          legend.text = element_text(size=14),
          legend.position="bottom") +
    labs(title = "Comparison of p-values generated from simulated data against p-values from real data for metabolite abundance \nat individual visit, and their respective FDR calculated values, generated by fitting an interaction model.",
         x = "Individual Metabolite",
         y = "P-value") + 
    geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.3) +
    geom_point(data=long_filt_data[which(long_filt_data$type =="real_pvalue"),], aes(x = name, y = value, fill = "real_pvalue", group=type), shape=17, size=3.5) +
    scale_fill_manual("real data p-values \noutside range", values=rep(1,9), guide=guide_legend(override.aes = list(colour=c("#ff62bc")))) + 
    guides(colour = guide_legend(override.aes = list(shape = 20))) +
    annotate(geom = "text", x = sig_data$name, y = sig_data$`value:gdm_pvalue` - 0.03, label = rownames(sig_data), size = 5)
  plot
}

sim_inter_roc_plot <- function(long_data, long_filt_data, sig_data){
  plot <- long_data %>% mutate(name=factor(as.character(name),levels=unique(name))) %>%
    ggplot(aes(x = name, y = value, colour = type, group=type))  +
    geom_rect(xmin=0, xmax=98, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=98, xmax=168, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=168, xmax=171, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=171, xmax=180, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=180, xmax=189, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=189, xmax=192, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=192, xmax=208, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=208, xmax=213, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=213, xmax=222, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=222, xmax=225, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=225, xmax=227, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=227, xmax=228, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    annotate(geom="text", x=(xminval+xmaxval)/2, y=-0.07, label=as.factor(metgroup), size=5) +
    geom_point() + 
    geom_line(data=long_data[which(long_data$type != "real_pvalue"),], aes(x=name, y=value, group=type[which(type != "real_pvalue")])) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_text(size=14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(),
          axis.line = element_line(colour = "black", size=0.3),
          axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          plot.title = element_text(size=17),
          aspect.ratio=7/21,
          legend.title = element_text(face="bold", size=14), 
          legend.text = element_text(size=14),
          legend.position="bottom") +
    labs(title = "Comparison of p-values generated from simulated data against p-values from real data for rate of change \nin metabolite abundance, generated by fitting an interaction model.",
         x = "Individual Metabolite",
         y = "P-value") + 
    geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.3) +
    geom_point(data=long_filt_data[which(long_filt_data$type =="real_pvalue"),], aes(x = name, y = value, fill = "real_pvalue", group=type), shape=17, size=3.5) +
    scale_fill_manual("real data p-values \noutside range", values=rep(1,5), guide=guide_legend(override.aes = list(colour=c("#e76bf3")))) + 
    guides(colour = guide_legend(override.aes = list(shape = 20))) +
    annotate(geom = "text", x = sig_data$name, y = sig_data$`value:gdm_pvalue` - 0.03, label = rownames(sig_data), size = 5)
  plot
}

srfdr_inter_roc_plot <- function(long_data, long_filt_data, sig_data){
  plot <- long_data %>% mutate(name=factor(as.character(name),levels=unique(name))) %>%
    ggplot(aes(x = name, y = value, colour = type, group=type)) +
    geom_rect(xmin=0, xmax=98, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=98, xmax=168, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=168, xmax=171, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=171, xmax=180, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=180, xmax=189, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=189, xmax=192, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=192, xmax=208, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=208, xmax=213, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=213, xmax=222, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=222, xmax=225, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    geom_rect(xmin=225, xmax=227, ymin=-0.15, ymax=1,fill="white", colour=NA) +
    geom_rect(xmin=227, xmax=228, ymin=-0.15, ymax=1,fill="azure2", colour=NA, alpha=0.5) +
    annotate(geom="text", x=(xminval+xmaxval)/2, y=-0.07, label=as.factor(metgroup), size=5) +
    geom_point() + 
    geom_line(data=long_data[which(long_data$type != "real_pvalue"),], aes(x=name, y=value, group=type[which(type != "real_pvalue")])) +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_text(size=14),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(),
          axis.line = element_line(colour = "black", size=0.3),
          axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          plot.title = element_text(size=17),
          aspect.ratio=7/21,
          legend.title = element_text(face="bold", size=15), 
          legend.text = element_text(size=14),
          legend.position="bottom") +
    labs(title = "Comparison of p-values generated from simulated data against p-values from real data for rate of change \nin metabolite abundance, and their respective FDR calculated values, generated by fitting an interaction model.",
         x = "Individual Metabolite",
         y = "P-value") + 
    geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.3) +
    geom_point(data=long_filt_data[which(long_filt_data$type =="real_pvalue"),], aes(x = name, y = value, fill = "real_pvalue", group=type), shape=17, size=3.5) +
    scale_fill_manual("real data p-values \noutside range", values=rep(1,9), guide=guide_legend(override.aes = list(colour=c("#ff62bc")))) + 
    guides(colour = guide_legend(override.aes = list(shape = 20))) +
    annotate(geom = "text", x = sig_data$name, y = sig_data$`value:gdm_pvalue` - 0.03, label = rownames(sig_data), size = 5)
  plot
}
